server:
  port: ${SERVER_PORT:8000}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://164.132.193.85:5432/ficedb}
    username: ${SPRING_DATASOURCE_USERNAME:user_myself}
    password: ${SPRING_DATASOURCE_PASSWORD:hello_th3r3_P}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${APP_JWT_SECRET:fice-cooperative-secret-key-must-be-at-least-256-bits-long-for-hs256}
    expiration-ms: ${APP_JWT_EXPIRATION_MS:86400000}  # 24h

logging:
  level:
    com.ibos.fice: DEBUG
